version: 4.6.{build}
os: Visual Studio 2017
configuration: Release
init:
- git config --global core.autocrlf true
build_script:
- choco install "sonarscanner-msbuild-net46" -y
- powershell -Command SonarScanner.MSBuild.exe begin /k:"ProphetLamb-Organistion_antlr4cs" /o:"prophetlamb-organistion" /d:sonar.login="${env:SONAR_TOKEN}" /d:sonar.host.url="https://sonarcloud.io"
- cd build
- powershell -Command .\build.ps1 -GenerateTests -MavenRepo C:\MavenRepo -Logger "${env:ProgramFiles}\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" -Java6Home "${env:ProgramFiles}\Java\jdk1.7.0\jre"
- cd ..
- powershell -Command SonarScanner.MSBuild.exe end /d:sonar.login="${env:SONAR_TOKEN}"
test_script:
- vstest.console /logger:Appveyor /TestCaseFilter:"TestCategory=runtime-suite" "C:\projects\antlr4cs\runtime\CSharp\Antlr4.Runtime.Test\bin\%CONFIGURATION%\netstandard1.5\Antlr4.Runtime.Test.dll"
- vstest.console /logger:Appveyor /TestCaseFilter:"TestCategory=runtime-suite" "C:\projects\antlr4cs\runtime\CSharp\Antlr4.Runtime.Test\bin\%CONFIGURATION%\netstandard2.0\Antlr4.Runtime.Test.dll"
- vstest.console /logger:Appveyor /TestCaseFilter:"TestCategory=runtime-suite" "C:\projects\antlr4cs\runtime\CSharp\Antlr4.Runtime.Test\bin\%CONFIGURATION%\netstandard2.1\Antlr4.Runtime.Test.dll"
- vstest.console /logger:Appveyor /TestCaseFilter:"TestCategory=runtime-suite" "C:\projects\antlr4cs\runtime\CSharp\Antlr4.Runtime.Test\bin\%CONFIGURATION%\net45\Antlr4.Runtime.Test.dll"
- vstest.console /logger:Appveyor /TestCaseFilter:"TestCategory=runtime-suite" "C:\projects\antlr4cs\runtime\CSharp\Antlr4.Runtime.Test\bin\%CONFIGURATION%\net50\Antlr4.Runtime.Test.dll"
cache:
- C:\MavenRepo -> **\pom.xml
artifacts:
- path: build\nuget\*.nupkg
