version: 4.6.{build}
os: Visual Studio 2017
configuration: Release
init:
  - git config --global core.autocrlf true
build_script:
  - dotnet tool install -g dotnet-sonarscanner
  - dotnet sonarscanner begin /k:"ProphetLamb-Organistion_antlr4cs" /o:"prophetlamb-organistion" /d:sonar.login="${env:SONAR_TOKEN}" /d:sonar.host.url="https://sonarcloud.io"
  - cd build
  - powershell -Command .\build.ps1 -GenerateTests -MavenRepo ".\artifacts\MavenRepo" -Java6Home "${env:ProgramFiles}\Java\jdk1.7.0\jre"
  - cd ..
  - dotnet sonarscanner end /d:sonar.login="${env:SONAR_TOKEN}"
test_script:
  - dotnet test --nologo --no-build --filter "TestCategory=runtime-suite" --logger:"Appveyor;LogFilePath=.\artifacts\coverage.opencover.xml" ".\runtime\CSharp\Antlr4.Runtime.Test\"
cache:
  - .\artifacts\MavenRepo -> **\pom.xml
artifacts:
  - path: .\artifacts\**\*.*
